### ISSUE TITLE
Cryptocompare API connection refused

### ISSUE THREAD

**Issue by D-Nice** [ethereum/meteor-package-tools#5]
I don't believe this api is active or at least not public anymore.

`GET https://min-api.cryptocompare.com/data/price?fsym=ETH&tsyms=BTC,USD,EUR net::ERR_CONNECTION_REFUSED`

A USD alternative would be etherscan's: 
`https://api.etherscan.io/api?module=stats&action=ethprice`

Ethereum:tools gets added because I am using ethereum:elements on the clientside.

**Comment by dukye** [comment]
+1

**Comment by evertonfraga** [comment]
I've just run it and got proper response:
`{"BTC":0.1006,"USD":770.61,"EUR":611.18,"BRL":2570.33,"GBP":551.68}`

Would you please confirm the frequency of requests your IP is generating? That could include other computers under the same network.

**Comment by D-Nice** [comment]
Directly polling it does appear to work for me now, so should be fair to assume it'll work with the tools.

**Comment by frozeman** [comment]
This API is free, but rate limited...
